---

- name: install packages
  apt:
    name: "{{item}}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - curl
  - python-pip

- name: install docker
  shell: "curl -sSL https://get.docker.com/ | sh"
  args:
    executable: /bin/bash

- name: create all users
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: install docker-compose
  pip:
    name: docker-compose
    state: latest

...
