---
- name: remove distribution packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

- name: install packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python2-pip

- name: Add Docker key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Install docker repo
  yum_repository:
    name: docker-ce
    description: Docker-ce YUM repo
    file: docker-ce_repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes

- name: install docker
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: create all users
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: install docker-compose
  pip:
    name: "{{ required_python_packages }}"
    extra_args: --upgrade
    executable: pip
  vars:
    required_python_packages:
    - docker-compose

...
