---
- name: remove distribution packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

- name: install packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add Docker key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: install docker repo
  yum_repository:
    name: docker-ce
    description: Docker-ce YUM repo
    file: docker-ce_repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes

- name: install docker
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: create all users
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: start docker daemon
  systemd:
    name: docker
    state: started
    enabled: yes

- name: install Docker Compose
  block:

  - name: install docker-compose dependencies
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - curl

  - name: fetch latest docker-compose version
    shell: curl -s -o /dev/null -I -w "%{redirect_url}\n" https://github.com/docker/compose/releases/latest | grep -oP "[0-9]+(\.[0-9]+)+$"
    args:
      executable: /bin/bash
    register: docker_compose_version

  - name: install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version.stdout }}/docker-compose-Linux-x86_64
      dest: /usr/bin/docker-compose
      mode: 0755

  when: docker_install_compose == True
...
