---
- name: remove distribution packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

- name: install packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Install docker repo
  yum_repository:
    name: docker-ce
    description: Docker-ce YUM repo
    file: docker-ce_repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes

- name: install docker
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: create all users
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: start docker daemon
  systemd:
    name: docker
    state: started
    enabled: yes

- name: install packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - python3-pip
    - python3-devel
    - python3-setuptools
    - openssl-devel
    - libgcc
    - libffi-devel
  when: docker_install_compose == True

- name: install docker-compose
  pip:
    name: "{{ required_python_packages }}"
    extra_args: --upgrade
    executable: pip3
  vars:
    required_python_packages:
    - docker-compose
  when: docker_install_compose == True

...
