---
- hosts: all
  become: true
  become_method: sudo

  vars:
    docker_users:
    - vagrant

  roles:
  - andrelohmann.root_colored_prompt
  - ansible-role-docker

  tasks:
  - name: Docker | Hello world
    ansible.builtin.command: docker run hello-world
...
