---
- name: Install
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:
    docker_users:
    - vagrant

  roles:
  - name: andrelohmann.root_colored_prompt
  - name: ansible-role-docker

  tasks:
  - name: Docker | Hello world
    ansible.builtin.command: docker run hello-world
...
