---

- name: Systemctl | Stop docker.socket
  ansible.builtin.systemd:
    name: docker.socket
    state: stopped

# Pause for 15 seconds to let unicorn restart
- name: Pause | Wait for 15 seconds
  ansible.builtin.pause:
    seconds: 15

- name: Systemctl | Stop docker.service
  ansible.builtin.systemd:
    name: docker.service
    state: stopped

# Pause for 15 seconds to let unicorn restart
- name: Pause | Wait for 15 seconds
  ansible.builtin.pause:
    seconds: 15

- name: Systemctl | Start docker.socket
  ansible.builtin.systemd:
    name: docker.socket
    state: started

# Pause for 15 seconds to let unicorn restart
- name: Pause | Wait for 15 seconds
  ansible.builtin.pause:
    seconds: 15

- name: Systemctl | Start docker.service
  ansible.builtin.systemd:
    name: docker.service
    state: started

...
