---

- name: Systemctl | Stop docker.socket
  ansible.builtin.systemd:
    name: docker.socket
    state: stopped
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Systemctl | Stop docker.service
  ansible.builtin.systemd:
    name: docker.service
    state: stopped
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Systemctl | Start docker.socket
  ansible.builtin.systemd:
    name: docker.socket
    state: started
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Systemctl | Start docker.service
  ansible.builtin.systemd:
    name: docker.service
    state: started
  register: result
  retries: 3
  delay: 10
  until: result is not failed

...
