---
- name: Converge
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars:
    docker_users:
    - ubuntu
  tasks:
  - name: Include andrelohmann.docker
    ansible.builtin.include_role:
      name: "andrelohmann.docker"
...
