---
- name: Converge
  hosts: all
  become: true
  become_method: sudo
  vars:
    docker_users:
    - ubuntu
  tasks:
  - name: "Include andrelohmann.docker"
    include_role:
      name: "andrelohmann.docker"
...
