---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Get Service Status
    ansible.builtin.shell: docker --version
    register: docker_version

  - name: dump postgresql service
    ansible.builtin.debug:
      var: docker_version

  - name: Assert postgresql.service is enabled
    ansible.builtin.assert:
      that:
      - "'Docker version' in docker_version.stdout"
      - "', build' in docker_version.stdout"
...
